//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace DA
{
    using System;
    using System.Collections.Generic;
    
    public partial class cooperativeeventassign
    {
        public int id { get; set; }
        public Nullable<int> ParentId { get; set; }
        public Nullable<int> Assigner { get; set; }
        public Nullable<System.DateTime> AssignTime { get; set; }
        public Nullable<int> TeacherMainId { get; set; }
        public Nullable<System.DateTime> CompleteDate { get; set; }
        public string Comments { get; set; }
        public Nullable<System.DateTime> ReplyFirstTime { get; set; }
        public Nullable<System.DateTime> ReplyLastTime { get; set; }
    }
}
