//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace DA
{
    using System;
    using System.Collections.Generic;
    
    public partial class course
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public course()
        {
            this.course_appendix = new HashSet<course_appendix>();
            this.course_designate = new HashSet<course_designate>();
            this.course_signup = new HashSet<course_signup>();
        }
    
        public int Seq { get; set; }
        public string CourseName { get; set; }
        public string CourseNumber { get; set; }
        public string CourseImage { get; set; }
        public string CourseImageType { get; set; }
        public string StartTime { get; set; }
        public string EndTime { get; set; }
        public Nullable<int> FunctionCategory { get; set; }
        public Nullable<int> TrainingGoal { get; set; }
        public string OtherTrainingGoal { get; set; }
        public Nullable<int> LecturerType { get; set; }
        public Nullable<int> Lecturer { get; set; }
        public Nullable<int> OtherLecturer { get; set; }
        public int TrainingObject { get; set; }
        public string OtherTrainingObject { get; set; }
        public int OpenSignUp { get; set; }
        public int AllowExternal { get; set; }
        public int CourseSurvey1 { get; set; }
        public int CourseSurvey2 { get; set; }
        public int CourseSurvey3 { get; set; }
        public string CourseMemo { get; set; }
        public string AuthorName { get; set; }
        public string AuthorMemo { get; set; }
        public string AuthorImage { get; set; }
        public string AuthorImageType { get; set; }
        public string CourseFocus { get; set; }
        public Nullable<int> QuestionNums { get; set; }
        public int CourseRelease { get; set; }
        public string ReleaseDate { get; set; }
        public System.DateTime CreatDate { get; set; }
        public int CreatUser { get; set; }
        public Nullable<System.DateTime> ModifyDate { get; set; }
        public Nullable<int> ModifyUser { get; set; }
        public int DeleteTag { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<course_appendix> course_appendix { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<course_designate> course_designate { get; set; }
        public virtual function_category function_category { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<course_signup> course_signup { get; set; }
        public virtual training_goal training_goal { get; set; }
        public virtual training_object training_object { get; set; }
    }
}
