//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace DA
{
    using System;
    using System.Collections.Generic;
    
    public partial class creditclasssignup
    {
        public int Seq { get; set; }
        public Nullable<int> CreditClassSeq { get; set; }
        public string Name { get; set; }
        public Nullable<System.DateTime> Birthday { get; set; }
        public string IdCardNo { get; set; }
        public string Email { get; set; }
        public Nullable<bool> IsOC { get; set; }
        public Nullable<bool> IsLowIncome { get; set; }
        public Nullable<bool> JobStatus { get; set; }
        public string SchoolName { get; set; }
        public string DepartmentName { get; set; }
        public Nullable<bool> IsNewGraduate { get; set; }
        public string GraduateYear { get; set; }
        public Nullable<int> EquEduStatus { get; set; }
        public string ServiceUnitName { get; set; }
        public string Position { get; set; }
        public string Tel { get; set; }
        public string Mobile { get; set; }
        public string ResAddr { get; set; }
        public string CommAddr { get; set; }
        public string ReferrerName { get; set; }
        public string EmgContact { get; set; }
        public string EmgMobile { get; set; }
        public string EmgRelation { get; set; }
        public string FacePicFile { get; set; }
        public string GraduFile { get; set; }
        public string WorkFile { get; set; }
        public string ReviewFile { get; set; }
        public string OCFile { get; set; }
        public Nullable<bool> IsTrans { get; set; }
        public Nullable<System.DateTime> CreateTime { get; set; }
        public Nullable<int> CreateUserSeq { get; set; }
        public Nullable<System.DateTime> ModifyTime { get; set; }
        public Nullable<int> ModifyUserSeq { get; set; }
        public string TelMeg { get; set; }
    }
}
