//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace DA
{
    using System;
    using System.Collections.Generic;
    
    public partial class creditclass
    {
        public int Seq { get; set; }
        public string Semester { get; set; }
        public Nullable<int> CreditClassPlaceSeq { get; set; }
        public string ClassId { get; set; }
        public Nullable<int> TeacherMainId { get; set; }
        public Nullable<System.DateTime> CreateTime { get; set; }
        public Nullable<int> CreateUserSeq { get; set; }
        public Nullable<System.DateTime> ModifyTime { get; set; }
        public Nullable<int> ModifyUserSeq { get; set; }
        public string Course1 { get; set; }
        public string Course2 { get; set; }
        public string Course3 { get; set; }
        public string Course4 { get; set; }
        public string Course5 { get; set; }
        public string Course6 { get; set; }
        public string Course7 { get; set; }
        public string Course8 { get; set; }
        public string Course9 { get; set; }
        public string Course10 { get; set; }
        public string Course11 { get; set; }
        public string Course12 { get; set; }
        public string Course13 { get; set; }
    }
}
