//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace DA
{
    using System;
    using System.Collections.Generic;
    
    public partial class expert_data
    {
        public int Seq { get; set; }
        public string Name { get; set; }
        public string Area { get; set; }
        public int Gender { get; set; }
        public string Identity { get; set; }
        public string IdentityCard { get; set; }
        public string Birthday { get; set; }
        public string Diet { get; set; }
        public string Telephone { get; set; }
        public string Mobile { get; set; }
        public string Mail { get; set; }
        public string Address { get; set; }
        public string ServiceAgency { get; set; }
        public string JobTitle { get; set; }
        public string AgencyPhone { get; set; }
        public string AgencyAddress { get; set; }
        public string Expertise { get; set; }
        public string Memo { get; set; }
        public string Education { get; set; }
        public string Experience { get; set; }
        public string ProjectExperience { get; set; }
        public System.DateTime CreatDate { get; set; }
        public int CreatUser { get; set; }
        public Nullable<System.DateTime> ModifyDate { get; set; }
        public Nullable<int> ModifyUser { get; set; }
        public int DeleteTag { get; set; }
        public string ExpertMemo { get; set; }
        public string ExpertImage { get; set; }
        public string ExpertImageType { get; set; }
    }
}
