//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace DA
{
    using System;
    using System.Collections.Generic;
    
    public partial class recommend_class
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public recommend_class()
        {
            this.recommend_class_log = new HashSet<recommend_class_log>();
        }
    
        public int Seq { get; set; }
        public string CourseCategory { get; set; }
        public string CourseSubcategory { get; set; }
        public string CourseTitle { get; set; }
        public string CourseTime { get; set; }
        public string Participants { get; set; }
        public string Deadline { get; set; }
        public string CourseIntroduction { get; set; }
        public string CourseURL { get; set; }
        public Nullable<System.DateTime> CreatDate { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<recommend_class_log> recommend_class_log { get; set; }
    }
}
