//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace DA
{
    using System;
    using System.Collections.Generic;
    
    public partial class studentmain
    {
        public int id { get; set; }
        public Nullable<int> SchoolYear { get; set; }
        public string SDegree { get; set; }
        public string SchoolId { get; set; }
        public string PeopleId { get; set; }
        public string SName { get; set; }
        public Nullable<System.DateTime> Birthday { get; set; }
        public string EMail { get; set; }
        public string Phone { get; set; }
        public string PhoneExt { get; set; }
        public string ServiceUnit { get; set; }
        public string JobTitle { get; set; }
        public string RegAddress { get; set; }
        public string ComAddress { get; set; }
        public string Note { get; set; }
        public string IsValid { get; set; }
        public Nullable<int> CreditClassSignUpSeq { get; set; }
        public Nullable<int> Creater { get; set; }
        public Nullable<System.DateTime> CreateTime { get; set; }
        public Nullable<int> Updater { get; set; }
        public Nullable<System.DateTime> UpdateTime { get; set; }
        public Nullable<int> CommonAdvisorId { get; set; }
        public Nullable<int> AdvisorId { get; set; }
        public Nullable<int> UserSeq { get; set; }
        public string SignatureFile { get; set; }
        public Nullable<bool> IsGraduate { get; set; }
    }
}
