//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace DA
{
    using System;
    using System.Collections.Generic;
    
    public partial class unit
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public unit()
        {
            this.annual_course_planning = new HashSet<annual_course_planning>();
            this.course_designate = new HashSet<course_designate>();
            this.course_designate1 = new HashSet<course_designate>();
        }
    
        public int Seq { get; set; }
        public string Name { get; set; }
        public string NameEN { get; set; }
        public string Abbreviation { get; set; }
        public string Code { get; set; }
        public string PhoneNumber { get; set; }
        public Nullable<int> ParentSeq { get; set; }
        public Nullable<int> Level { get; set; }
        public Nullable<int> OrderNo { get; set; }
        public System.DateTime CreatDate { get; set; }
        public int CreatUser { get; set; }
        public int IsActive { get; set; }
        public int DeleteTag { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<annual_course_planning> annual_course_planning { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<course_designate> course_designate { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<course_designate> course_designate1 { get; set; }
    }
}
