//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace DA
{
    using System;
    using System.Collections.Generic;
    
    public partial class user
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public user()
        {
            this.course_signup = new HashSet<course_signup>();
        }
    
        public int UserSeq { get; set; }
        public string UserWorkNum { get; set; }
        public string UserName { get; set; }
        public string UserAccount { get; set; }
        public string UserPassword { get; set; }
        public int UserRole { get; set; }
        public string UserMobile { get; set; }
        public string Extension { get; set; }
        public string UserMail { get; set; }
        public int UserUnit { get; set; }
        public Nullable<int> UserJobTitle { get; set; }
        public Nullable<int> Management { get; set; }
        public Nullable<System.DateTime> StratWorkDay { get; set; }
        public System.DateTime CreatDate { get; set; }
        public int CreatUser { get; set; }
        public int IsActive { get; set; }
        public int DeleteTag { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<course_signup> course_signup { get; set; }
    }
}
